name: release-please

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT (aws-actions/configure-aws-credentials)
  contents: write # to create release commit (google-github-actions/release-please-action)
  pull-requests: write # to create release PR (google-github-actions/release-please-action)

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # The "release" step invokes on every merge to 'main' branch
      # and collects pending changes in pending release PR.
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # Steps below publish released packages to npm.
      # They only trigger after release-please PR from previous step is merged to main.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935785792371:role/GithubNpmPublishAction
          role-session-name: language-server-runtimes-github
          aws-region: us-east-1
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - name: Get npm access token
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            npmjs/github_automation
          parse-json-secrets: true
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@aws'
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - name: Set token
        run: echo "NODE_AUTH_TOKEN=${{ env.NPMJS_GITHUB_AUTOMATION_TOKEN }}" >> $GITHUB_ENV
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - name: Compile and test packages
        run: |
          npm clean-install
          npm run compile
          npm run test
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - name: Publish Chat Client UI Types to npm
        run: npm run pub --workspace chat-client-ui-types
        if: ${{ steps.release.outputs['chat-client-ui-types--release_created'] }}

      - name: Publish Runtimes to npm
        run: npm run pub --workspace runtimes
        if: ${{ steps.release.outputs['runtimes--release_created'] }}

      - name: Publish Types to npm
        run: npm run pub --workspace types
        if: ${{ steps.release.outputs['types--release_created'] }}